# Generated by Django 4.2.7 on 2023-11-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MYTEC', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
